### ISSUE TITLE
[Build Phase Error] Use of undeclared type 'AppDelegate'

### ISSUE THREAD

**Issue by diegodurli** [bh5-pods/react-native-gcm#1]
Hi @euforic!

I'm new to iOS and React Native programming, therefore, I've been trying to have a basic project using your library and I couldn't. 

Basically, it's saying that 'AppDelegate' is not being found on the project, which is strange. Following, some pictures.

This is happening at GCM.swift. Perhaps, am I doing some wrong setup?
![screen shot 2015-07-24 at 6 43 47 pm](https://cloud.githubusercontent.com/assets/1239143/8885308/bd509906-3234-11e5-8201-e62cb44035ee.png)

This is my project setup.
![screen shot 2015-07-24 at 6 44 06 pm](https://cloud.githubusercontent.com/assets/1239143/8885309/bd7f5b88-3234-11e5-8f24-402e8bd78ab2.png)

As you can see, this is more a help than a issue properly. Really not sure. Hopefully you can help me out to setup a basic project using your library! Amazing job by the way, thanks!

**Comment by olliebrennan** [comment]
I have ran into this exact error.  The POD and node module install just fine but when I import the GCM files into the project I receive the same error.

It maybe something simple but it looks like the swift file is missing its dependencies?

Really appreciate any help! Cheers

**Comment by euforic** [comment]
Sorry I need to update the docs and note it is a bit bleeding edge. I have updated things to work with the latest version of swift so and Reactnative so that might be part of the issue. I am also waiting on google to update the GCM pod so this can be used as a frameworks see [http://stackoverflow.com/questions/30910852/the-pods-target-has-transitive-dependencies-that-include-static-binaries-whe](http://stackoverflow.com/questions/30910852/the-pods-target-has-transitive-dependencies-that-include-static-binaries-whe).

With that said, try adding your  project to the bridge AppDelegate header to the bridge header and see if that solves things.

**Comment by diegodurli** [comment]
Hi @euforic! I've tried several combinations of possible solutions but it did not worked at all. I was wondering, could you please share your currently working example? This would help a lot to see the possible differences. Thank you!

**Comment by olliebrennan** [comment]
Same here. Upgrading to native v0.8.0 does not resolve. (not sure on how / if to update swift).

Interestingly, adding my projects AppDelegate to the bridge header changes things up a little
<img width="983" alt="screenshot 2015-07-29 09 04 28" src="https://cloud.githubusercontent.com/assets/669978/8946120/28e59f28-35d1-11e5-8242-6f6220e4c31a.png">

**Comment by JakeRawr** [comment]
Hi, @euforic 

Is there any update for this issue?

**Comment by JonnyBGod** [comment]
+1

**Comment by euforic** [comment]
The problem is obj-c needs to know about the AppDelegate extension. See http://stackoverflow.com/questions/27097688/can-objective-c-code-call-swift-extension-on-class

**Comment by deminoth** [comment]
I added `#import "AppDelegate.h"` to the bridging header and now it's ok.

**Comment by mihaisee** [comment]
Hi, did anyone with this problem managed to find a solution? I have the same issue and I can't manage to make this work. Can someone give an example on how they successfully run this? Thanks.

**Comment by shishircc** [comment]
Hi @mihaisee , please see the #6 for solution in comments
