### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by richarddewit** [bh5-pods/react-native-gcm#6]
I'm close, I can feel it...

I have done:

- `npm install react-native-gcm`
- Installed CocoaPods
- `pod init`
- Opened `ProjectName.xcworkspace` instead of `ProjectName.xcodeproj`
- Added GCM Pod to `Podfile`:
``` ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ProjectName' do
  pod 'Google/CloudMessaging'
end

target 'ProjectNameTests' do

end
```
- `pod install`
- Added Source files to project
    * GCM.swift
    * GCMBridge.h
    * GCMBridge.m
- Added ObjC / Swift Bridge Header (`ProjectName-Bridging-Header.h`):
``` objective-c
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

#import "AppDelegate.h"

#import "RCTBridge.h"
#import "RCTBridgeModule.h"
#import "RCTEventDispatcher.h"
#import <Google/CloudMessaging.h>
```

After this I got errors in `GCM.swift` saying:
```
Method 'application(_:didRegisterForRemoteNotificationsWithDeviceToken:)' with
  Objective-C selector 'application:didRegisterForRemoteNotificationsWithDeviceToken:'
  conflicts with previous declaration with the same Objective-C selector

Method 'application(_:didFailToRegisterForRemoteNotificationsWithError:)' with
  Objective-C selector 'application:didFailToRegisterForRemoteNotificationsWithError:'
  conflicts with previous declaration with the same Objective-C selector

Method 'application(_:didReceiveRemoteNotification:fetchCompletionHandler:)' with
  Objective-C selector 'application:didReceiveRemoteNotification:fetchCompletionHandler:'
  conflicts with previous declaration with the same Objective-C selector
```

so I made those functions `private` to solve the errors (`private func application(` instead of `func application(`) as [mentioned here](http://stackoverflow.com/a/29670644/1062281).

But now I get these errors:
```
Undefined symbols for architecture armv7:
  "_kGGLInstanceIDScopeGCM", referenced from:
      ProjectName.GCM._appDidRegisterForRemoteNotifications (ProjectName.GCM)(__ObjC.NSNotification) -> () in GCM.o
      ProjectName.GCM.onTokenRefresh (ProjectName.GCM)() -> () in GCM.o
      ProjectName.GCM.unregister (ProjectName.GCM)(([Swift.AnyObject]!) -> ()) -> () in GCM.o
  "_kGGLInstanceIDRegisterAPNSOption", referenced from:
      ProjectName.GCM._appDidRegisterForRemoteNotifications (ProjectName.GCM)(__ObjC.NSNotification) -> () in GCM.o
  "_kGGLInstanceIDAPNSServerTypeSandboxOption", referenced from:
      ProjectName.GCM._appDidRegisterForRemoteNotifications (ProjectName.GCM)(__ObjC.NSNotification) -> () in GCM.o
  "_OBJC_CLASS_$_GGLInstanceIDConfig", referenced from:
      type metadata accessor for __ObjC.GGLInstanceIDConfig in GCM.o
  "_OBJC_CLASS_$_GGLContext", referenced from:
      type metadata accessor for __ObjC.GGLContext in GCM.o
  "_OBJC_CLASS_$_GCMService", referenced from:
      type metadata accessor for __ObjC.GCMService in GCM.o
  "_OBJC_CLASS_$_GGLConfiguration", referenced from:
      type metadata accessor for __ObjC.GGLConfiguration in GCM.o
  "_OBJC_CLASS_$_GGLInstanceID", referenced from:
      type metadata accessor for __ObjC.GGLInstanceID in GCM.o
  "_OBJC_CLASS_$_GCMPubSub", referenced from:
      type metadata accessor for __ObjC.GCMPubSub in GCM.o
  "_OBJC_CLASS_$_GCMConfig", referenced from:
      type metadata accessor for __ObjC.GCMConfig in GCM.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

![image](https://cloud.githubusercontent.com/assets/7933750/11361960/0c221174-9291-11e5-988f-1277c44c957c.png)

I now have no idea what to do.. I do not know either Obj-C or Swift :(

**Comment by shishircc** [comment]
@euforic , any suggestion on this ? I also face same problem.

**Comment by shishircc** [comment]
@richarddewit , did you find any solution to this ? 

I suspect that Xcode 7 which was released recently upgraded Swift Language to version 2, breaking old code. That's what we are encountering. 

It's kind of sad that such breaking changes make developer experience pretty bad.

**Comment by richarddewit** [comment]
@shishircc - no I'm using RN's own [`PushNotificationIOS`](https://facebook.github.io/react-native/docs/pushnotificationios.html) instead. To setup GCM you need an APNS certificate anyway, and my backend can handle both APNS and GCM at once. `PushNotificationIOS` suffices for me.

**Comment by shishircc** [comment]
For those facing this issue, other than following the steps that @richarddewit listed (such as using the pod workspace instead of project file after doing the pod install, uncommenting use framework etc), you can additionally do following 

Go to Build Settings for your project
1. In Other Linker Flags have $(inherited)
2. In Enable Modules have Yes
3. Say NO to Enable Bitcode in your target Build Settings 

These steps resolved the issue for me 

References 
https://github.com/gonzaloaune/GCMPushPlugin/issues/3
http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

**Comment by PhilippKrone** [comment]
Is there any solution for this issue?

**Comment by shishircc** [comment]
Yes, a solution from web worked for me. I was able to get the app compiling
and running.

See my comments on github to resolve the issue.

**Comment by euforic** [comment]
I am going close this just to avoid confusion. @shishircc comment above should help resolve the issue.
